version: '3.3'

services:
  db:
    image: akrov/notedb
    container_name: "db"
    restart: always
    ports:
      - "3306:3306"    

  note:
    image: akrov/note
    container_name: "note"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "db"


